### ISSUE TITLE
Recommend creating separate repositories

### ISSUE THREAD

**Issue by yding02** [ajfinley/ESWBerkeley#1]
Hi,

I recommend creating separate repositories for each individual project rather than having them as branches of one repository. This would allow easier use of branches for each individual project as well as fewer accidents. I have already forked this repository, and I will push changes onto here on a frequent basis, but not directly onto here.

**Comment by ajfinley** [comment]
Separate repositories was our original approach. Would it be preferable to create an ESW account that owns each repository, and add project members/leaders as collaborators?

**Comment by yding02** [comment]
I think the organization solution is good!
